name: Test Vagrant Automation
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04  # Explicitly use Ubuntu 24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y virtualbox wget
          wget https://releases.hashicorp.com/vagrant/2.4.0/vagrant_2.4.0-1_amd64.deb
          sudo dpkg -i vagrant_2.4.0-1_amd64.deb
          vagrant --version  # Verify installation

      - name: Start Vagrant and Test Provisioning
        run: |
          vagrant up --provision
          curl -s http://192.168.56.20 | grep "Hello dear,This is Mayokun-DevOps Setting up Nginx-Server automatedly with Vagrant!"  # Verify Nginx
          vagrant destroy -f  # Cleanup