name: Test Vagrant Automation
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y virtualbox wget
          wget https://releases.hashicorp.com/vagrant/2.4.7/vagrant_2.4.7-1_amd64.deb
          sudo dpkg -i vagrant_2.4.7-1_amd64.deb
          vagrant --version

      - name: Run Vagrant Provisioning
        run: |
          sudo mkdir -p /root/.vagrant.d
          sudo cp -R $HOME/.vagrant.d/* /root/.vagrant.d/ 2>/dev/null || true
          sudo vagrant up --provision
          
          # Improved verification
          HTTP_OUTPUT=$(curl -s http://192.168.56.20)
          echo "$HTTP_OUTPUT"  # Debug output
          echo "$HTTP_OUTPUT" | grep -q "Mayokun-DevOps" || exit 1
          
          sudo vagrant destroy -f